-- ============================================================================
-- Third batch: 120 more exercises from WorkoutX (40 barbell + 40 dumbbell +
-- 40 cable), continuing from 0144/0145. Excludes everything used in those
-- two migrations (by WorkoutX id) plus the 3 one-off gif-sync fixes done
-- earlier this session outside those migrations (close_grip_lat_pulldown/
-- 2616, lat_pulldown/0198, face_pull/5203) — several near-duplicate
-- pulldown variants got filtered out by name because of those 3. Base rows
-- only — gif_url/instructions/secondary_muscles filled right after via
-- exercise-gif-sync, one call per row.
-- ============================================================================

insert into exercises (slug, name, muscle_group, equipment) values
  ('barbell_seated_close_grip_behind_neck_triceps_extension', 'Barbell Seated Close Grip Behind Neck Triceps Extension', 'triceps', 'barbell'),
  ('barbell_reverse_grip_skullcrusher', 'Barbell Reverse Grip Skullcrusher', 'triceps', 'barbell'),
  ('barbell_pin_presses', 'Barbell Pin Presses', 'triceps', 'barbell'),
  ('barbell_standing_concentration_curl', 'Barbell Standing Concentration Curl', 'biceps', 'barbell'),
  ('barbell_sitted_alternate_leg_raise', 'Barbell Sitted Alternate Leg Raise', 'core', 'barbell'),
  ('barbell_sitted_alternate_leg_raise_female', 'Barbell Sitted Alternate Leg Raise (female)', 'core', 'barbell'),
  ('landmine_lateral_raise', 'Landmine Lateral Raise', 'shoulders', 'barbell'),
  ('barbell_bench_front_squat', 'Barbell Bench Front Squat', 'quads', 'barbell'),
  ('barbell_clean_and_press', 'Barbell Clean and Press', 'quads', 'barbell'),
  ('barbell_clean_grip_front_squat', 'Barbell Clean-grip Front Squat', 'glutes', 'barbell'),
  ('barbell_decline_wide_grip_press', 'Barbell Decline Wide-grip Press', 'chest', 'barbell'),
  ('barbell_front_chest_squat', 'Barbell Front Chest Squat', 'glutes', 'barbell'),
  ('barbell_full_squat', 'Barbell Full Squat', 'glutes', 'barbell'),
  ('barbell_guillotine_bench_press', 'Barbell Guillotine Bench Press', 'chest', 'barbell'),
  ('barbell_jm_bench_press', 'Barbell Jm Bench Press', 'triceps', 'barbell'),
  ('barbell_jump_squat', 'Barbell Jump Squat', 'glutes', 'barbell'),
  ('barbell_lying_close_grip_press', 'Barbell Lying Close-grip Press', 'triceps', 'barbell'),
  ('barbell_lying_close_grip_triceps_extension', 'Barbell Lying Close-grip Triceps Extension', 'triceps', 'barbell'),
  ('barbell_lying_extension', 'Barbell Lying Extension', 'triceps', 'barbell'),
  ('barbell_lying_lifting_on_hip', 'Barbell Lying Lifting (on Hip)', 'glutes', 'barbell'),
  ('barbell_lying_preacher_curl', 'Barbell Lying Preacher Curl', 'biceps', 'barbell'),
  ('barbell_lying_triceps_extension_skull_crusher', 'Barbell Lying Triceps Extension Skull Crusher', 'triceps', 'barbell'),
  ('barbell_lying_triceps_extension', 'Barbell Lying Triceps Extension', 'triceps', 'barbell'),
  ('barbell_narrow_stance_squat', 'Barbell Narrow Stance Squat', 'glutes', 'barbell'),
  ('barbell_one_arm_floor_press', 'Barbell One Arm Floor Press', 'triceps', 'barbell'),
  ('barbell_one_arm_side_deadlift', 'Barbell One Arm Side Deadlift', 'glutes', 'barbell'),
  ('barbell_one_leg_squat', 'Barbell One Leg Squat', 'quads', 'barbell'),
  ('barbell_overhead_squat', 'Barbell Overhead Squat', 'quads', 'barbell'),
  ('barbell_press_sit_up', 'Barbell Press Sit-up', 'core', 'barbell'),
  ('barbell_rack_pull', 'Barbell Rack Pull', 'glutes', 'barbell'),
  ('barbell_rear_delt_row', 'Barbell Rear Delt Row', 'shoulders', 'barbell'),
  ('barbell_rear_lunge_v2', 'Barbell Rear Lunge V2', 'glutes', 'barbell'),
  ('barbell_rear_lunge', 'Barbell Rear Lunge', 'glutes', 'barbell'),
  ('barbell_seated_behind_head_military_press', 'Barbell Seated Behind Head Military Press', 'shoulders', 'barbell'),
  ('barbell_seated_bradford_rocky_press', 'Barbell Seated Bradford Rocky Press', 'shoulders', 'barbell'),
  ('barbell_seated_good_morning', 'Barbell Seated Good Morning', 'glutes', 'barbell'),
  ('barbell_seated_overhead_press', 'Barbell Seated Overhead Press', 'shoulders', 'barbell'),
  ('barbell_side_split_squat_v2', 'Barbell Side Split Squat V2', 'quads', 'barbell'),
  ('barbell_side_split_squat', 'Barbell Side Split Squat', 'quads', 'barbell'),
  ('barbell_single_leg_split_squat', 'Barbell Single Leg Split Squat', 'quads', 'barbell'),
  ('dumbbell_incline_twisted_flyes', 'Dumbbell Incline Twisted Flyes', 'chest', 'dumbbell'),
  ('dumbbell_iron_cross', 'Dumbbell Iron Cross', 'shoulders', 'dumbbell'),
  ('dumbbell_lateral_to_front_raise', 'Dumbbell Lateral to Front Raise', 'shoulders', 'dumbbell'),
  ('dumbbell_lying_extension_across_face', 'Dumbbell Lying Extension (across Face)', 'triceps', 'dumbbell'),
  ('dumbbell_lying_elbow_press', 'Dumbbell Lying Elbow Press', 'triceps', 'dumbbell'),
  ('dumbbell_lying_femoral', 'Dumbbell Lying Femoral', 'hamstrings', 'dumbbell'),
  ('dumbbell_lying_hammer_press', 'Dumbbell Lying Hammer Press', 'chest', 'dumbbell'),
  ('dumbbell_lying_one_arm_deltoid_rear', 'Dumbbell Lying One Arm Deltoid Rear', 'shoulders', 'dumbbell'),
  ('dumbbell_lying_one_arm_press_v2', 'Dumbbell Lying One Arm Press V2', 'chest', 'dumbbell'),
  ('dumbbell_lying_one_arm_press', 'Dumbbell Lying One Arm Press', 'chest', 'dumbbell'),
  ('dumbbell_lying_one_arm_pronated_triceps_extension', 'Dumbbell Lying One Arm Pronated Triceps Extension', 'triceps', 'dumbbell'),
  ('dumbbell_lying_one_arm_rear_lateral_raise', 'Dumbbell Lying One Arm Rear Lateral Raise', 'shoulders', 'dumbbell'),
  ('dumbbell_lying_one_arm_supinated_triceps_extension', 'Dumbbell Lying One Arm Supinated Triceps Extension', 'triceps', 'dumbbell'),
  ('dumbbell_lying_pronation', 'Dumbbell Lying Pronation', 'forearms', 'dumbbell'),
  ('dumbbell_lying_rear_lateral_raise', 'Dumbbell Lying Rear Lateral Raise', 'shoulders', 'dumbbell'),
  ('dumbbell_lying_supination', 'Dumbbell Lying Supination', 'forearms', 'dumbbell'),
  ('dumbbell_lying_supine_curl', 'Dumbbell Lying Supine Curl', 'biceps', 'dumbbell'),
  ('dumbbell_lying_triceps_extension', 'Dumbbell Lying Triceps Extension', 'triceps', 'dumbbell'),
  ('dumbbell_neutral_grip_bench_press', 'Dumbbell Neutral Grip Bench Press', 'triceps', 'dumbbell'),
  ('dumbbell_one_arm_lateral_raise_with_support', 'Dumbbell One Arm Lateral Raise with Support', 'shoulders', 'dumbbell'),
  ('dumbbell_one_arm_reverse_fly_with_support', 'Dumbbell One Arm Reverse Fly (with Support)', 'shoulders', 'dumbbell'),
  ('dumbbell_one_arm_shoulder_press_v2', 'Dumbbell One Arm Shoulder Press V2', 'shoulders', 'dumbbell'),
  ('dumbbell_over_bench_neutral_wrist_curl', 'Dumbbell Over Bench Neutral Wrist Curl', 'biceps', 'dumbbell'),
  ('dumbbell_over_bench_one_arm_neutral_wrist_curl', 'Dumbbell Over Bench One Arm Neutral Wrist Curl', 'biceps', 'dumbbell'),
  ('dumbbell_over_bench_one_arm_wrist_curl', 'Dumbbell Over Bench One Arm Wrist Curl', 'forearms', 'dumbbell'),
  ('dumbbell_over_bench_reverse_wrist_curl', 'Dumbbell Over Bench Reverse Wrist Curl', 'forearms', 'dumbbell'),
  ('dumbbell_over_bench_wrist_curl', 'Dumbbell Over Bench Wrist Curl', 'forearms', 'dumbbell'),
  ('dumbbell_preacher_hammer_curl', 'Dumbbell Preacher Hammer Curl', 'biceps', 'dumbbell'),
  ('dumbbell_plyo_squat', 'Dumbbell Plyo Squat', 'glutes', 'dumbbell'),
  ('dumbbell_pronate_grip_triceps_extension', 'Dumbbell Pronate-grip Triceps Extension', 'triceps', 'dumbbell'),
  ('dumbbell_raise', 'Dumbbell Raise', 'shoulders', 'dumbbell'),
  ('dumbbell_rear_delt_row_shoulder', 'Dumbbell Rear Delt Row (shoulder)', 'shoulders', 'dumbbell'),
  ('dumbbell_rear_fly', 'Dumbbell Rear Fly', 'shoulders', 'dumbbell'),
  ('dumbbell_rear_lateral_raise_support_head', 'Dumbbell Rear Lateral Raise (support Head)', 'shoulders', 'dumbbell'),
  ('dumbbell_rear_lateral_raise', 'Dumbbell Rear Lateral Raise', 'shoulders', 'dumbbell'),
  ('dumbbell_rear_lunge', 'Dumbbell Rear Lunge', 'glutes', 'dumbbell'),
  ('dumbbell_reverse_grip_biceps_curl', 'Dumbbell Reverse Grip Biceps Curl', 'biceps', 'dumbbell'),
  ('dumbbell_reverse_fly', 'Dumbbell Reverse Fly', 'shoulders', 'dumbbell'),
  ('dumbbell_rotation_reverse_fly', 'Dumbbell Rotation Reverse Fly', 'shoulders', 'dumbbell'),
  ('dumbbell_seated_alternate_front_raise', 'Dumbbell Seated Alternate Front Raise', 'shoulders', 'dumbbell'),
  ('cable_one_arm_fly_on_exercise_ball', 'Cable One Arm Fly on Exercise Ball', 'chest', 'cable'),
  ('cable_one_arm_incline_fly_on_exercise_ball', 'Cable One Arm Incline Fly on Exercise Ball', 'chest', 'cable'),
  ('cable_close_grip_curl', 'Cable Close Grip Curl', 'biceps', 'cable'),
  ('cable_overhead_curl', 'Cable Overhead Curl', 'biceps', 'cable'),
  ('cable_overhead_curl_on_exercise_ball', 'Cable Overhead Curl on Exercise Ball', 'biceps', 'cable'),
  ('cable_pulldown_bicep_curl', 'Cable Pulldown Bicep Curl', 'biceps', 'cable'),
  ('cable_rope_hammer_preacher_curl', 'Cable Rope Hammer Preacher Curl', 'biceps', 'cable'),
  ('cable_rope_one_arm_hammer_preacher_curl', 'Cable Rope One Arm Hammer Preacher Curl', 'biceps', 'cable'),
  ('cable_seated_curl', 'Cable Seated Curl', 'biceps', 'cable'),
  ('cable_seated_one_arm_concentration_curl', 'Cable Seated One Arm Concentration Curl', 'biceps', 'cable'),
  ('cable_seated_overhead_curl', 'Cable Seated Overhead Curl', 'biceps', 'cable'),
  ('cable_two_arm_curl_on_incline_bench', 'Cable Two Arm Curl on Incline Bench', 'biceps', 'cable'),
  ('cable_high_pulley_overhead_tricep_extension', 'Cable High Pulley Overhead Tricep Extension', 'triceps', 'cable'),
  ('cable_one_arm_tricep_pushdown', 'Cable One Arm Tricep Pushdown', 'triceps', 'cable'),
  ('cable_rope_high_pulley_overhead_tricep_extension', 'Cable Rope High Pulley Overhead Tricep Extension', 'triceps', 'cable'),
  ('cable_rope_incline_tricep_extension', 'Cable Rope Incline Tricep Extension', 'triceps', 'cable'),
  ('cable_standing_reverse_grip_one_arm_overhead_tricep_extension', 'Cable Standing Reverse Grip One Arm Overhead Tricep Extension', 'triceps', 'cable'),
  ('cable_two_arm_tricep_kickback', 'Cable Two Arm Tricep Kickback', 'triceps', 'cable'),
  ('inverse_leg_curl_on_pull_up_cable_machine', 'Inverse Leg Curl (on Pull-up Cable Machine)', 'hamstrings', 'cable'),
  ('cable_reverse_grip_triceps_pushdown_sz_bar_with_arm_blaster', 'Cable Reverse Grip Triceps Pushdown (sz-bar) (with Arm Blaster)', 'triceps', 'cable'),
  ('alternate_lateral_pulldown', 'Alternate Lateral Pulldown', 'back', 'cable'),
  ('cable_alternate_shoulder_press', 'Cable Alternate Shoulder Press', 'shoulders', 'cable'),
  ('cable_cross_over_lateral_pulldown', 'Cable Cross-over Lateral Pulldown', 'back', 'cable'),
  ('cable_cross_over_variation', 'Cable Cross-over Variation', 'chest', 'cable'),
  ('cable_decline_seated_wide_grip_row', 'Cable Decline Seated Wide-grip Row', 'back', 'cable'),
  ('cable_floor_seated_wide_grip_row', 'Cable Floor Seated Wide-grip Row', 'back', 'cable'),
  ('cable_incline_pushdown', 'Cable Incline Pushdown', 'back', 'cable'),
  ('cable_lying_close_grip_curl', 'Cable Lying Close-grip Curl', 'biceps', 'cable'),
  ('cable_lying_extension_pullover_with_rope_attachment', 'Cable Lying Extension Pullover (with Rope Attachment)', 'back', 'cable'),
  ('cable_lying_fly', 'Cable Lying Fly', 'chest', 'cable'),
  ('cable_lying_triceps_extension_v2', 'Cable Lying Triceps Extension V2', 'triceps', 'cable'),
  ('cable_one_arm_lateral_bent_over', 'Cable One Arm Lateral Bent-over', 'chest', 'cable'),
  ('cable_one_arm_straight_back_high_row_kneeling', 'Cable One Arm Straight Back High Row (kneeling)', 'back', 'cable'),
  ('cable_pull_through_with_rope', 'Cable Pull Through (with Rope)', 'glutes', 'cable'),
  ('cable_pushdown_straight_arm_v2', 'Cable Pushdown (straight Arm) V2', 'back', 'cable'),
  ('cable_rear_delt_row_stirrups', 'Cable Rear Delt Row (stirrups)', 'shoulders', 'cable'),
  ('cable_rear_delt_row_with_rope', 'Cable Rear Delt Row (with Rope)', 'shoulders', 'cable'),
  ('cable_rear_pulldown', 'Cable Rear Pulldown', 'back', 'cable'),
  ('cable_reverse_grip_straight_back_seated_high_row', 'Cable Reverse-grip Straight Back Seated High Row', 'back', 'cable'),
  ('cable_seated_one_arm_alternate_row', 'Cable Seated One Arm Alternate Row', 'back', 'cable');
