-- ============================================================================
-- Closes out barbell/dumbbell/cable from WorkoutX: every remaining exercise
-- not already covered by 0144/0145/0146, our existing catalog, or the 3
-- one-off gif-sync fixes — 193 rows (36 barbell + 125 dumbbell + 32 cable;
-- started at 196 genuinely-missing, minus 3 near-duplicates the canon()
-- dedup missed: 'Dumbbell Alternate Preacher Curl' vs our existing
-- 'Alternating Preacher Curl (Dumbbell)', 'Farmers Walk' vs our existing
-- "Farmer's Walk" (apostrophe-splitting bug in canon()), and one WorkoutX
-- internal duplicate id for the same exercise). This finishes these 3
-- equipment types entirely. Base rows only — gif_url/instructions/
-- secondary_muscles filled right after via exercise-gif-sync.
-- ============================================================================

insert into exercises (slug, name, muscle_group, equipment) values
  ('barbell_skier', 'Barbell Skier', 'shoulders', 'barbell'),
  ('barbell_speed_squat', 'Barbell Speed Squat', 'glutes', 'barbell'),
  ('barbell_standing_bradford_press', 'Barbell Standing Bradford Press', 'shoulders', 'barbell'),
  ('barbell_stiff_leg_good_morning', 'Barbell Stiff Leg Good Morning', 'glutes', 'barbell'),
  ('barbell_straight_leg_deadlift', 'Barbell Straight Leg Deadlift', 'hamstrings', 'barbell'),
  ('barbell_sumo_deadlift', 'Barbell Sumo Deadlift', 'glutes', 'barbell'),
  ('barbell_reverse_grip_bent_over_row', 'Barbell Reverse Grip Bent Over Row', 'back', 'barbell'),
  ('barbell_upright_row_v2', 'Barbell Upright Row V2', 'shoulders', 'barbell'),
  ('barbell_upright_row_v3', 'Barbell Upright Row V3', 'shoulders', 'barbell'),
  ('barbell_wide_bench_press', 'Barbell Wide Bench Press', 'chest', 'barbell'),
  ('barbell_wide_grip_upright_row', 'Barbell Wide-grip Upright Row', 'shoulders', 'barbell'),
  ('barbell_wide_squat', 'Barbell Wide Squat', 'quads', 'barbell'),
  ('barbell_zercher_squat', 'Barbell Zercher Squat', 'glutes', 'barbell'),
  ('cambered_bar_lying_row', 'Cambered Bar Lying Row', 'back', 'barbell'),
  ('squat_jerk', 'Squat Jerk', 'quads', 'barbell'),
  ('standing_behind_neck_press', 'Standing Behind Neck Press', 'shoulders', 'barbell'),
  ('barbell_reverse_grip_decline_bench_press', 'Barbell Reverse Grip Decline Bench Press', 'chest', 'barbell'),
  ('barbell_reverse_grip_incline_bench_press', 'Barbell Reverse Grip Incline Bench Press', 'chest', 'barbell'),
  ('barbell_wide_reverse_grip_bench_press', 'Barbell Wide Reverse Grip Bench Press', 'chest', 'barbell'),
  ('barbell_reverse_grip_incline_bench_row', 'Barbell Reverse Grip Incline Bench Row', 'back', 'barbell'),
  ('barbell_lateral_lunge', 'Barbell Lateral Lunge', 'glutes', 'barbell'),
  ('kneeling_jump_squat', 'Kneeling Jump Squat', 'glutes', 'barbell'),
  ('barbell_low_bar_squat', 'Barbell Low Bar Squat', 'glutes', 'barbell'),
  ('barbell_high_bar_squat', 'Barbell High Bar Squat', 'glutes', 'barbell'),
  ('barbell_standing_close_grip_military_press', 'Barbell Standing Close Grip Military Press', 'shoulders', 'barbell'),
  ('barbell_standing_wide_military_press', 'Barbell Standing Wide Military Press', 'shoulders', 'barbell'),
  ('barbell_full_zercher_squat', 'Barbell Full Zercher Squat', 'glutes', 'barbell'),
  ('barbell_incline_close_grip_bench_press', 'Barbell Incline Close Grip Bench Press', 'triceps', 'barbell'),
  ('barbell_lying_back_of_the_head_tricep_extension', 'Barbell Lying Back of the Head Tricep Extension', 'triceps', 'barbell'),
  ('barbell_single_leg_deadlift', 'Barbell Single Leg Deadlift', 'glutes', 'barbell'),
  ('barbell_reverse_close_grip_bench_press', 'Barbell Reverse Close-grip Bench Press', 'triceps', 'barbell'),
  ('barbell_squat_jump_step_rear_lunge', 'Barbell Squat Jump Step Rear Lunge', 'quads', 'barbell'),
  ('barbell_split_squat_v2', 'Barbell Split Squat V2', 'quads', 'barbell'),
  ('barbell_pendlay_row', 'Barbell Pendlay Row', 'back', 'barbell'),
  ('frankenstein_squat', 'Frankenstein Squat', 'glutes', 'barbell'),
  ('barbell_glute_bridge_two_legs_on_bench_male', 'Barbell Glute Bridge Two Legs on Bench (male)', 'glutes', 'barbell'),
  ('dumbbell_seated_alternate_press', 'Dumbbell Seated Alternate Press', 'shoulders', 'dumbbell'),
  ('dumbbell_seated_bench_extension', 'Dumbbell Seated Bench Extension', 'triceps', 'dumbbell'),
  ('dumbbell_seated_biceps_curl_on_stability_ball', 'Dumbbell Seated Biceps Curl (on Stability Ball)', 'biceps', 'dumbbell'),
  ('dumbbell_seated_front_raise', 'Dumbbell Seated Front Raise', 'shoulders', 'dumbbell'),
  ('dumbbell_seated_inner_biceps_curl', 'Dumbbell Seated Inner Biceps Curl', 'biceps', 'dumbbell'),
  ('dumbbell_seated_kickback', 'Dumbbell Seated Kickback', 'triceps', 'dumbbell'),
  ('dumbbell_seated_lateral_raise_v2', 'Dumbbell Seated Lateral Raise V2', 'shoulders', 'dumbbell'),
  ('dumbbell_seated_lateral_raise', 'Dumbbell Seated Lateral Raise', 'shoulders', 'dumbbell'),
  ('dumbbell_seated_neutral_wrist_curl', 'Dumbbell Seated Neutral Wrist Curl', 'biceps', 'dumbbell'),
  ('dumbbell_seated_one_arm_rotate', 'Dumbbell Seated One Arm Rotate', 'forearms', 'dumbbell'),
  ('dumbbell_seated_one_leg_calf_raise', 'Dumbbell Seated One Leg Calf Raise', 'calves', 'dumbbell'),
  ('dumbbell_seated_palms_up_wrist_curl', 'Dumbbell Seated Palms Up Wrist Curl', 'forearms', 'dumbbell'),
  ('dumbbell_seated_preacher_curl', 'Dumbbell Seated Preacher Curl', 'biceps', 'dumbbell'),
  ('dumbbell_seated_reverse_grip_concentration_curl', 'Dumbbell Seated Reverse Grip Concentration Curl', 'biceps', 'dumbbell'),
  ('dumbbell_side_lying_one_hand_raise', 'Dumbbell Side Lying One Hand Raise', 'shoulders', 'dumbbell'),
  ('dumbbell_single_leg_calf_raise', 'Dumbbell Single Leg Calf Raise', 'calves', 'dumbbell'),
  ('dumbbell_standing_alternate_overhead_press', 'Dumbbell Standing Alternate Overhead Press', 'shoulders', 'dumbbell'),
  ('dumbbell_standing_alternate_raise', 'Dumbbell Standing Alternate Raise', 'shoulders', 'dumbbell'),
  ('dumbbell_standing_biceps_curl', 'Dumbbell Standing Biceps Curl', 'biceps', 'dumbbell'),
  ('dumbbell_standing_front_raise_above_head', 'Dumbbell Standing Front Raise Above Head', 'shoulders', 'dumbbell'),
  ('dumbbell_standing_kickback', 'Dumbbell Standing Kickback', 'triceps', 'dumbbell'),
  ('dumbbell_standing_one_arm_curl_over_incline_bench', 'Dumbbell Standing One Arm Curl (over Incline Bench)', 'biceps', 'dumbbell'),
  ('dumbbell_standing_one_arm_extension', 'Dumbbell Standing One Arm Extension', 'triceps', 'dumbbell'),
  ('dumbbell_standing_one_arm_palm_in_press', 'Dumbbell Standing One Arm Palm in Press', 'shoulders', 'dumbbell'),
  ('dumbbell_standing_one_arm_reverse_curl', 'Dumbbell Standing One Arm Reverse Curl', 'biceps', 'dumbbell'),
  ('dumbbell_standing_overhead_press', 'Dumbbell Standing Overhead Press', 'shoulders', 'dumbbell'),
  ('dumbbell_standing_palms_in_press', 'Dumbbell Standing Palms in Press', 'shoulders', 'dumbbell'),
  ('dumbbell_standing_preacher_curl', 'Dumbbell Standing Preacher Curl', 'biceps', 'dumbbell'),
  ('dumbbell_straight_arm_pullover', 'Dumbbell Straight Arm Pullover', 'chest', 'dumbbell'),
  ('dumbbell_straight_leg_deadlift', 'Dumbbell Straight Leg Deadlift', 'glutes', 'dumbbell'),
  ('dumbbell_w_press', 'Dumbbell W-press', 'shoulders', 'dumbbell'),
  ('dumbbell_zottman_curl', 'Dumbbell Zottman Curl', 'biceps', 'dumbbell'),
  ('push_up_close_grip_off_dumbbell', 'Push-up Close-grip Off Dumbbell', 'triceps', 'dumbbell'),
  ('spell_caster', 'Spell Caster', 'core', 'dumbbell'),
  ('dumbbell_lying_external_shoulder_rotation', 'Dumbbell Lying External Shoulder Rotation', 'shoulders', 'dumbbell'),
  ('dumbbell_upright_shoulder_external_rotation', 'Dumbbell Upright Shoulder External Rotation', 'shoulders', 'dumbbell'),
  ('dumbbell_incline_one_arm_press', 'Dumbbell Incline One Arm Press', 'chest', 'dumbbell'),
  ('dumbbell_incline_one_arm_press_on_exercise_ball', 'Dumbbell Incline One Arm Press on Exercise Ball', 'chest', 'dumbbell'),
  ('dumbbell_lying_pullover_on_exercise_ball', 'Dumbbell Lying Pullover on Exercise Ball', 'chest', 'dumbbell'),
  ('dumbbell_one_arm_bench_fly', 'Dumbbell One Arm Bench Fly', 'chest', 'dumbbell'),
  ('dumbbell_one_arm_chest_fly_on_exercise_ball', 'Dumbbell One Arm Chest Fly on Exercise Ball', 'chest', 'dumbbell'),
  ('dumbbell_one_arm_press_on_exercise_ball', 'Dumbbell One Arm Press on Exercise Ball', 'chest', 'dumbbell'),
  ('dumbbell_one_arm_pullover_on_exercise_ball', 'Dumbbell One Arm Pullover on Exercise Ball', 'chest', 'dumbbell'),
  ('dumbbell_pullover_hip_extension_on_exercise_ball', 'Dumbbell Pullover Hip Extension on Exercise Ball', 'chest', 'dumbbell'),
  ('dumbbell_lying_rear_delt_row', 'Dumbbell Lying Rear Delt Row', 'back', 'dumbbell'),
  ('dumbbell_palm_rotational_bent_over_row', 'Dumbbell Palm Rotational Bent Over Row', 'back', 'dumbbell'),
  ('dumbbell_reverse_grip_incline_bench_one_arm_row', 'Dumbbell Reverse Grip Incline Bench One Arm Row', 'back', 'dumbbell'),
  ('dumbbell_reverse_grip_incline_bench_two_arm_row', 'Dumbbell Reverse Grip Incline Bench Two Arm Row', 'back', 'dumbbell'),
  ('dumbbell_seated_one_leg_calf_raise_hammer_grip', 'Dumbbell Seated One Leg Calf Raise - Hammer Grip', 'calves', 'dumbbell'),
  ('dumbbell_seated_one_leg_calf_raise_palm_up', 'Dumbbell Seated One Leg Calf Raise - Palm Up', 'calves', 'dumbbell'),
  ('exercise_ball_on_the_wall_calf_raise', 'Exercise Ball on the Wall Calf Raise', 'calves', 'dumbbell'),
  ('dumbbell_one_arm_reverse_grip_press', 'Dumbbell One Arm Reverse Grip Press', 'chest', 'dumbbell'),
  ('dumbbell_palms_in_incline_bench_press', 'Dumbbell Palms in Incline Bench Press', 'triceps', 'dumbbell'),
  ('dumbbell_reverse_bench_press', 'Dumbbell Reverse Bench Press', 'chest', 'dumbbell'),
  ('dumbbell_alternate_hammer_preacher_curl', 'Dumbbell Alternate Hammer Preacher Curl', 'biceps', 'dumbbell'),
  ('dumbbell_alternate_seated_hammer_curl', 'Dumbbell Alternate Seated Hammer Curl', 'biceps', 'dumbbell'),
  ('dumbbell_alternating_seated_bicep_curl_on_exercise_ball', 'Dumbbell Alternating Seated Bicep Curl on Exercise Ball', 'biceps', 'dumbbell'),
  ('dumbbell_bicep_curl_lunge_with_bowling_motion', 'Dumbbell Bicep Curl Lunge with Bowling Motion', 'biceps', 'dumbbell'),
  ('dumbbell_bicep_curl_on_exercise_ball_with_leg_raised', 'Dumbbell Bicep Curl on Exercise Ball with Leg Raised', 'biceps', 'dumbbell'),
  ('dumbbell_bicep_curl_with_stork_stance', 'Dumbbell Bicep Curl with Stork Stance', 'biceps', 'dumbbell'),
  ('dumbbell_biceps_curl_reverse', 'Dumbbell Biceps Curl Reverse', 'biceps', 'dumbbell'),
  ('dumbbell_biceps_curl_squat', 'Dumbbell Biceps Curl Squat', 'biceps', 'dumbbell'),
  ('dumbbell_biceps_curl_v_sit_on_bosu_ball', 'Dumbbell Biceps Curl V Sit on Bosu Ball', 'biceps', 'dumbbell'),
  ('dumbbell_cross_body_hammer_curl_v2', 'Dumbbell Cross Body Hammer Curl V2', 'biceps', 'dumbbell'),
  ('dumbbell_lunge_with_bicep_curl', 'Dumbbell Lunge with Bicep Curl', 'biceps', 'dumbbell'),
  ('dumbbell_lying_supine_biceps_curl', 'Dumbbell Lying Supine Biceps Curl', 'biceps', 'dumbbell'),
  ('dumbbell_lying_wide_curl', 'Dumbbell Lying Wide Curl', 'biceps', 'dumbbell'),
  ('dumbbell_high_curl', 'Dumbbell High Curl', 'biceps', 'dumbbell'),
  ('dumbbell_one_arm_prone_curl', 'Dumbbell One Arm Prone Curl', 'biceps', 'dumbbell'),
  ('dumbbell_one_arm_prone_hammer_curl', 'Dumbbell One Arm Prone Hammer Curl', 'biceps', 'dumbbell'),
  ('dumbbell_one_arm_reverse_spider_curl', 'Dumbbell One Arm Reverse Spider Curl', 'biceps', 'dumbbell'),
  ('dumbbell_one_arm_seated_bicep_curl_on_exercise_ball', 'Dumbbell One Arm Seated Bicep Curl on Exercise Ball', 'biceps', 'dumbbell'),
  ('dumbbell_one_arm_seated_hammer_curl', 'Dumbbell One Arm Seated Hammer Curl', 'biceps', 'dumbbell'),
  ('dumbbell_one_arm_standing_hammer_curl', 'Dumbbell One Arm Standing Hammer Curl', 'biceps', 'dumbbell'),
  ('dumbbell_one_arm_zottman_preacher_curl', 'Dumbbell One Arm Zottman Preacher Curl', 'biceps', 'dumbbell'),
  ('dumbbell_preacher_curl_over_exercise_ball', 'Dumbbell Preacher Curl Over Exercise Ball', 'biceps', 'dumbbell'),
  ('dumbbell_prone_incline_hammer_curl', 'Dumbbell Prone Incline Hammer Curl', 'biceps', 'dumbbell'),
  ('dumbbell_seated_alternate_hammer_curl_on_exercise_ball', 'Dumbbell Seated Alternate Hammer Curl on Exercise Ball', 'biceps', 'dumbbell'),
  ('dumbbell_seated_bicep_curl', 'Dumbbell Seated Bicep Curl', 'biceps', 'dumbbell'),
  ('dumbbell_seated_one_arm_bicep_curl_on_exercise_ball_with_leg_raised', 'Dumbbell Seated One Arm Bicep Curl on Exercise Ball with Leg Raised', 'biceps', 'dumbbell'),
  ('dumbbell_step_up_single_leg_balance_with_bicep_curl', 'Dumbbell Step Up Single Leg Balance with Bicep Curl', 'biceps', 'dumbbell'),
  ('dumbbell_push_press', 'Dumbbell Push Press', 'shoulders', 'dumbbell'),
  ('dumbbell_lying_alternate_extension', 'Dumbbell Lying Alternate Extension', 'triceps', 'dumbbell'),
  ('dumbbell_seated_bent_over_alternate_kickback', 'Dumbbell Seated Bent Over Alternate Kickback', 'triceps', 'dumbbell'),
  ('dumbbell_forward_lunge_triceps_extension', 'Dumbbell Forward Lunge Triceps Extension', 'triceps', 'dumbbell'),
  ('dumbbell_incline_two_arm_extension', 'Dumbbell Incline Two Arm Extension', 'triceps', 'dumbbell'),
  ('dumbbell_kickbacks_on_exercise_ball', 'Dumbbell Kickbacks on Exercise Ball', 'triceps', 'dumbbell'),
  ('dumbbell_seated_bent_over_triceps_extension', 'Dumbbell Seated Bent Over Triceps Extension', 'triceps', 'dumbbell'),
  ('dumbbell_seated_reverse_grip_one_arm_overhead_tricep_extension', 'Dumbbell Seated Reverse Grip One Arm Overhead Tricep Extension', 'triceps', 'dumbbell'),
  ('dumbbell_standing_alternating_tricep_kickback', 'Dumbbell Standing Alternating Tricep Kickback', 'triceps', 'dumbbell'),
  ('dumbbell_standing_bent_over_one_arm_triceps_extension', 'Dumbbell Standing Bent Over One Arm Triceps Extension', 'triceps', 'dumbbell'),
  ('dumbbell_standing_bent_over_two_arm_triceps_extension', 'Dumbbell Standing Bent Over Two Arm Triceps Extension', 'triceps', 'dumbbell'),
  ('dumbbell_tricep_kickback_with_stork_stance', 'Dumbbell Tricep Kickback with Stork Stance', 'triceps', 'dumbbell'),
  ('dumbbell_twisting_bench_press', 'Dumbbell Twisting Bench Press', 'triceps', 'dumbbell'),
  ('exercise_ball_supine_triceps_extension', 'Exercise Ball Supine Triceps Extension', 'triceps', 'dumbbell'),
  ('dumbbell_single_leg_deadlift', 'Dumbbell Single Leg Deadlift', 'glutes', 'dumbbell'),
  ('biceps_leg_concentration_curl', 'Biceps Leg Concentration Curl', 'biceps', 'dumbbell'),
  ('dumbbell_cuban_press_v2', 'Dumbbell Cuban Press V2', 'shoulders', 'dumbbell'),
  ('dumbbell_standing_around_world', 'Dumbbell Standing Around World', 'shoulders', 'dumbbell'),
  ('dumbbell_seated_triceps_extension', 'Dumbbell Seated Triceps Extension', 'triceps', 'dumbbell'),
  ('dumbbells_seated_triceps_extension', 'Dumbbells Seated Triceps Extension', 'triceps', 'dumbbell'),
  ('dumbbell_standing_zottman_preacher_curl', 'Dumbbell Standing Zottman Preacher Curl', 'biceps', 'dumbbell'),
  ('dumbbell_seated_bent_arm_lateral_raise', 'Dumbbell Seated Bent Arm Lateral Raise', 'shoulders', 'dumbbell'),
  ('dumbbell_standing_inner_biceps_curl_v2', 'Dumbbell Standing Inner Biceps Curl V2', 'biceps', 'dumbbell'),
  ('dumbbell_reverse_grip_row_female', 'Dumbbell Reverse Grip Row (female)', 'back', 'dumbbell'),
  ('dumbbell_scott_press', 'Dumbbell Scott Press', 'shoulders', 'dumbbell'),
  ('dumbbell_hammer_curls_with_arm_blaster', 'Dumbbell Hammer Curls (with Arm Blaster)', 'biceps', 'dumbbell'),
  ('dumbbell_lying_on_floor_rear_delt_raise', 'Dumbbell Lying on Floor Rear Delt Raise', 'shoulders', 'dumbbell'),
  ('dumbbell_lying_pronation_on_floor', 'Dumbbell Lying Pronation on Floor', 'forearms', 'dumbbell'),
  ('dumbbell_lying_supination_on_floor', 'Dumbbell Lying Supination on Floor', 'forearms', 'dumbbell'),
  ('dumbbell_step_up_lunge', 'Dumbbell Step-up Lunge', 'quads', 'dumbbell'),
  ('dumbbell_supported_squat', 'Dumbbell Supported Squat', 'quads', 'dumbbell'),
  ('dumbbell_single_leg_deadlift_with_stepbox_support', 'Dumbbell Single Leg Deadlift with Stepbox Support', 'glutes', 'dumbbell'),
  ('dumbbell_sumo_pull_through', 'Dumbbell Sumo Pull Through', 'glutes', 'dumbbell'),
  ('dumbbell_step_up_split_squat', 'Dumbbell Step-up Split Squat', 'quads', 'dumbbell'),
  ('hyght_dumbbell_fly', 'Hyght Dumbbell Fly', 'chest', 'dumbbell'),
  ('dumbbell_incline_y_raise', 'Dumbbell Incline Y-raise', 'back', 'dumbbell'),
  ('dumbbell_incline_t_raise', 'Dumbbell Incline T-raise', 'shoulders', 'dumbbell'),
  ('dumbbell_incline_alternate_press', 'Dumbbell Incline Alternate Press', 'chest', 'dumbbell'),
  ('dumbbell_seated_alternate_shoulder', 'Dumbbell Seated Alternate Shoulder', 'shoulders', 'dumbbell'),
  ('dumbbell_seated_biceps_curl_to_shoulder_press', 'Dumbbell Seated Biceps Curl to Shoulder Press', 'biceps', 'dumbbell'),
  ('dumbbell_single_arm_overhead_carry', 'Dumbbell Single Arm Overhead Carry', 'shoulders', 'dumbbell'),
  ('dumbbell_contralateral_forward_lunge', 'Dumbbell Contralateral Forward Lunge', 'glutes', 'dumbbell'),
  ('dumbbell_side_plank_with_rear_fly', 'Dumbbell Side Plank with Rear Fly', 'back', 'dumbbell'),
  ('dumbbell_waiter_biceps_curl', 'Dumbbell Waiter Biceps Curl', 'biceps', 'dumbbell'),
  ('cable_seated_shoulder_internal_rotation', 'Cable Seated Shoulder Internal Rotation', 'shoulders', 'cable'),
  ('cable_seated_wide_grip_row', 'Cable Seated Wide-grip Row', 'back', 'cable'),
  ('cable_standing_rear_delt_row_with_rope', 'Cable Standing Rear Delt Row (with Rope)', 'shoulders', 'cable'),
  ('cable_standing_shoulder_external_rotation', 'Cable Standing Shoulder External Rotation', 'shoulders', 'cable'),
  ('cable_standing_twist_row_v_bar', 'Cable Standing Twist Row (v-bar)', 'back', 'cable'),
  ('cable_straight_arm_pulldown_with_rope', 'Cable Straight Arm Pulldown (with Rope)', 'back', 'cable'),
  ('cable_straight_back_seated_row', 'Cable Straight Back Seated Row', 'back', 'cable'),
  ('cable_twisting_pull', 'Cable Twisting Pull', 'back', 'cable'),
  ('cable_underhand_pulldown', 'Cable Underhand Pulldown', 'back', 'cable'),
  ('twin_handle_parallel_grip_lat_pulldown', 'Twin Handle Parallel Grip Lat Pulldown', 'back', 'cable'),
  ('cable_decline_one_arm_press', 'Cable Decline One Arm Press', 'chest', 'cable'),
  ('cable_one_arm_incline_press', 'Cable One Arm Incline Press', 'chest', 'cable'),
  ('cable_one_arm_incline_press_on_exercise_ball', 'Cable One Arm Incline Press on Exercise Ball', 'chest', 'cable'),
  ('cable_one_arm_press_on_exercise_ball', 'Cable One Arm Press on Exercise Ball', 'chest', 'cable'),
  ('cable_standing_up_straight_crossovers', 'Cable Standing Up Straight Crossovers', 'chest', 'cable'),
  ('cable_upper_chest_crossovers', 'Cable Upper Chest Crossovers', 'chest', 'cable'),
  ('cable_incline_bench_row', 'Cable Incline Bench Row', 'back', 'cable'),
  ('cable_palm_rotational_row', 'Cable Palm Rotational Row', 'back', 'cable'),
  ('cable_rope_crossover_seated_row', 'Cable Rope Crossover Seated Row', 'back', 'cable'),
  ('cable_rope_extension_incline_bench_row', 'Cable Rope Extension Incline Bench Row', 'back', 'cable'),
  ('cable_rope_seated_row', 'Cable Rope Seated Row', 'back', 'cable'),
  ('cable_upper_row', 'Cable Upper Row', 'back', 'cable'),
  ('cable_wide_grip_rear_pulldown_behind_neck', 'Cable Wide Grip Rear Pulldown Behind Neck', 'back', 'cable'),
  ('cable_lying_bicep_curl', 'Cable Lying Bicep Curl', 'biceps', 'cable'),
  ('cable_squatting_curl', 'Cable Squatting Curl', 'biceps', 'cable'),
  ('cable_squat_row_with_rope_attachment', 'Cable Squat Row (with Rope Attachment)', 'back', 'cable'),
  ('cable_rope_lying_on_floor_tricep_extension', 'Cable Rope Lying on Floor Tricep Extension', 'triceps', 'cable'),
  ('cable_seated_chest_press', 'Cable Seated Chest Press', 'chest', 'cable'),
  ('cable_lat_pulldown_full_range_of_motion', 'Cable Lat Pulldown Full Range of Motion', 'back', 'cable'),
  ('cable_thibaudeau_kayak_row', 'Cable Thibaudeau Kayak Row', 'back', 'cable'),
  ('cable_assisted_inverse_leg_curl', 'Cable Assisted Inverse Leg Curl', 'hamstrings', 'cable'),
  ('cable_kneeling_rear_delt_row_with_rope_male', 'Cable Kneeling Rear Delt Row (with Rope) (male)', 'shoulders', 'cable');
