-- ============================================================================
-- Cleanup: 88 of migration 0149's 193 rows never got their gif_url/
-- instructions/secondary_muscles — exercise-gif-sync's WorkoutX gif fetch
-- returned 403 for these specific ids (confirmed permanent on retry, not a
-- transient rate limit; likely these specific assets sit behind a plan
-- tier WorkoutX's key doesn't currently have access to). Removing the
-- incomplete rows rather than leaving image-less, instruction-less
-- exercises live in the picker. The other 105 rows from 0149 are complete
-- and stay.
-- ============================================================================

delete from exercises where slug in (
  'dumbbell_cross_body_hammer_curl_v2',
  'dumbbell_lunge_with_bicep_curl',
  'dumbbell_lying_supine_biceps_curl',
  'dumbbell_lying_wide_curl',
  'dumbbell_high_curl',
  'dumbbell_one_arm_prone_curl',
  'dumbbell_one_arm_prone_hammer_curl',
  'dumbbell_one_arm_reverse_spider_curl',
  'dumbbell_one_arm_seated_bicep_curl_on_exercise_ball',
  'dumbbell_one_arm_seated_hammer_curl',
  'dumbbell_one_arm_standing_hammer_curl',
  'dumbbell_one_arm_zottman_preacher_curl',
  'dumbbell_preacher_curl_over_exercise_ball',
  'dumbbell_prone_incline_hammer_curl',
  'dumbbell_seated_alternate_hammer_curl_on_exercise_ball',
  'dumbbell_seated_bicep_curl',
  'dumbbell_seated_one_arm_bicep_curl_on_exercise_ball_with_leg_raised',
  'dumbbell_push_press',
  'dumbbell_lying_alternate_extension',
  'dumbbell_seated_bent_over_alternate_kickback',
  'dumbbell_forward_lunge_triceps_extension',
  'dumbbell_incline_two_arm_extension',
  'dumbbell_kickbacks_on_exercise_ball',
  'dumbbell_seated_bent_over_triceps_extension',
  'dumbbell_seated_reverse_grip_one_arm_overhead_tricep_extension',
  'dumbbell_standing_alternating_tricep_kickback',
  'dumbbell_standing_bent_over_one_arm_triceps_extension',
  'dumbbell_standing_bent_over_two_arm_triceps_extension',
  'dumbbell_tricep_kickback_with_stork_stance',
  'dumbbell_twisting_bench_press',
  'exercise_ball_supine_triceps_extension',
  'dumbbell_single_leg_deadlift',
  'biceps_leg_concentration_curl',
  'dumbbell_cuban_press_v2',
  'dumbbell_standing_around_world',
  'dumbbell_seated_triceps_extension',
  'dumbbells_seated_triceps_extension',
  'dumbbell_standing_zottman_preacher_curl',
  'dumbbell_seated_bent_arm_lateral_raise',
  'dumbbell_standing_inner_biceps_curl_v2',
  'dumbbell_reverse_grip_row_female',
  'dumbbell_scott_press',
  'dumbbell_hammer_curls_with_arm_blaster',
  'dumbbell_lying_on_floor_rear_delt_raise',
  'dumbbell_lying_pronation_on_floor',
  'dumbbell_lying_supination_on_floor',
  'dumbbell_step_up_lunge',
  'dumbbell_supported_squat',
  'dumbbell_single_leg_deadlift_with_stepbox_support',
  'dumbbell_sumo_pull_through',
  'dumbbell_step_up_split_squat',
  'hyght_dumbbell_fly',
  'dumbbell_incline_y_raise',
  'dumbbell_incline_t_raise',
  'dumbbell_incline_alternate_press',
  'dumbbell_seated_alternate_shoulder',
  'dumbbell_seated_biceps_curl_to_shoulder_press',
  'dumbbell_single_arm_overhead_carry',
  'dumbbell_contralateral_forward_lunge',
  'dumbbell_side_plank_with_rear_fly',
  'dumbbell_waiter_biceps_curl',
  'cable_seated_shoulder_internal_rotation',
  'cable_standing_rear_delt_row_with_rope',
  'cable_standing_shoulder_external_rotation',
  'cable_standing_twist_row_v_bar',
  'cable_straight_arm_pulldown_with_rope',
  'cable_twisting_pull',
  'cable_underhand_pulldown',
  'twin_handle_parallel_grip_lat_pulldown',
  'cable_decline_one_arm_press',
  'cable_one_arm_incline_press',
  'cable_one_arm_incline_press_on_exercise_ball',
  'cable_one_arm_press_on_exercise_ball',
  'cable_standing_up_straight_crossovers',
  'cable_incline_bench_row',
  'cable_palm_rotational_row',
  'cable_rope_crossover_seated_row',
  'cable_rope_extension_incline_bench_row',
  'cable_upper_row',
  'cable_wide_grip_rear_pulldown_behind_neck',
  'cable_lying_bicep_curl',
  'cable_squatting_curl',
  'cable_squat_row_with_rope_attachment',
  'cable_rope_lying_on_floor_tricep_extension',
  'cable_seated_chest_press',
  'cable_thibaudeau_kayak_row',
  'cable_assisted_inverse_leg_curl',
  'cable_kneeling_rear_delt_row_with_rope_male'
);
